[package]
name = "hello_nom"
version = "0.1.0"
authors = ["Wei Sun <waysun@amazon.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
