[package]
name = "hello_opencl"
version = "0.1.0"
authors = ["Sun, Wei <waysun@amazon.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ocl = "0.19"
ocl-core = "0.11.2"
futures = "*"